name: Terraform Release Pipeine (Reusable)
description: |
  This is a reusable GitHub Actions workflow for CI/CD using Terraform.
  It includes steps for linting, validating, scanning, and building AWS resources.
  The workflow is designed to be triggered by other workflows or manually.
  It also includes steps for checking environments, detecting changes, and preparing builds.

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to (e.g., ci, devl, test, prod)."
        required: true
        type: string
      terraform-dir:
        description: "Directory containing Terraform configuration files."
        required: true
        type: string
        default: "tf"
      tf-vars-file:
        description: "Terraform variables file to use."
        required: false
        type: string
        default: "terraform.tfvars"
      ci-pipeline:
        description: "Indicates if this is a CI pipeline run."
        required: false
        type: boolean
        default: true
    secrets:
      aws-role-arn:
        description: "AWS role ARN for assuming a role."
        required: true
      infracost-api-key:
        description: "API key for Infracost."
        required: true
      infracost-gist-id:
        description: "Gist ID for Infracost output."
        required: true

permissions:
  id-token: write
  contents: write
  # actions: read


jobs:

  execution-path:
    name: 🔎 Get Exec. Path
    runs-on: ubuntu-latest
    outputs:
      execution-path: ${{ steps.set-path.outputs.execution-path }}

    steps:
      - name: Set Execution Path
        id: set-path
        run: |
          echo "execution-path={\"IaC\": true, \"lambda\": true, \"lambda-layer\": false, \"glue\": false, \"state-machine\": false}" >> $GITHUB_OUTPUT

  terraform-validate:
    if: ${{ fromJSON(needs.execution-path.outputs.execution-path).IaC == true }}
    name: ✔️ Terraform Validate
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [execution-path]
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-role-arn }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Validation and Formatting Checks
        id: validate
        uses: subhamay-bhattacharyya-gha/tf-validate-action@main
        with:
          terraform-dir: ${{ inputs.terraform-dir }}              
          s3-bucket: ${{ vars.TF_STATE_BUCKET_NAME }}
          s3-region: ${{ vars.AWS_REGION }}
          ci-pipeline: "true"
          soft-fail: "true"                                  

  terraform-lint:
    name: 📋 Terraform Lint
    runs-on: ubuntu-latest
    needs: [execution-path]
    if: ${{ fromJSON(needs.execution-path.outputs.execution-path).IaC == true }}
    steps:
      - name: Run TFLint
        uses: subhamay-bhattacharyya-gha/tf-lint-action@main
        with:
          tflint-ver: ${{ vars.TF_LINT_VER }}
          use-cache: "true"
          tflint-format: "compact"
          
  checkov-scan:
    if: ${{ fromJSON(needs.execution-path.outputs.execution-path).IaC == true }}
    name: 🧳 Checkov Scan
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [execution-path]
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-role-arn }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Checkov Scan
        uses: subhamay-bhattacharyya-gha/checkov-scan-action@main
        id: checkov-scan
        with:
          iac-dir: ${{ inputs.terraform-dir }}
          iac-framework: terraform
          soft-fail: true

      - name: Confirm SARIF file type
        shell: bash
        run: |
          ls -la "${{ github.workspace }}"
          file "${{ github.workspace }}/results.sarif"

      - name: "📋 Summarize and Print Checkov Scan Report with Snippets"
        id: summarize-report
        uses: subhamay-bhattacharyya-gha/checkov-report-action@main

  build-lambda:
    name: 🛠️ ⛔ Lambda Package
    if: ${{ toJSON(needs.execution-path.outputs.execution-path).lambda == true }}
    runs-on: ubuntu-latest
    needs: [execution-path]
    steps:
      - name: Build and Upload Lambda Package
        run: echo "Uploading Lambda package..."

  build-lambda-layer:
    name: 🛠️ ⛔ Lambda Layer
    if: ${{ toJSON(needs.execution-path.outputs.execution-path)['lambda-layer'] == true }}
    runs-on: ubuntu-latest
    needs: [execution-path]
    steps:
    
      - name: Build Lambda Layer Package
        run: echo "No changes in Lambda layer package, skipping build..."

      - name: Build and Upload Lambda Layer Package
        run: echo "Build and Upload Lambda layer...."

  build-glue:
    name: 🛠️ ⛔ Glue Script
    if: ${{ fromJSON(needs.execution-path.outputs.execution-path).glue == true }}
    runs-on: ubuntu-latest
    needs: [execution-path]
    
    steps:
      - name: Package Glue Script
        run: echo "No changes found in Glue script, skipping build..."

      - name: Package and Upload Glue Script
        run: echo "Uploading Glue script..."

  build-state-machine:
    name: 🛠️ ⛔ State Machine
    if: ${{ fromJSON(needs.execution-path.outputs.execution-path)['state-machine'] == true }}
    runs-on: ubuntu-latest
    needs: [execution-path]
    steps:

      - name: Package State Machine
        run: echo "No changes in State Machine, skipping build."

      - name: Upload State Machine ASL
        run: echo "Uploading State Machine ASL..."

  yor-resource-tagging:
    if: ${{ fromJSON(needs.execution-path.outputs.execution-path).IaC == true }}
    name: 📋 Apply Git Metadata Tags using YOR
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [ terraform-lint, terraform-validate, checkov-scan ]
    steps:
      - name: Call Yor Reusable Action
        run: echo "Applying Git metadata tags using YOR..."
        uses: subhamay-bhattacharyya-gha/tf-yor-action@main
        with:
          terraform-dir: ${{ inputs.terraform-dir }}
         
  terraform-plan:
    if: ${{ fromJSON(needs.execution-path.outputs.execution-path).IaC == true }}
    name: 📋 Terraform Plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [ yor-resource-tagging ]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-role-arn }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Plan
        id: plan
        uses: subhamay-bhattacharyya-gha/tf-plan-action@main
        with:
          terraform-dir: ${{ inputs.terraform-dir }} 
          tf-vars-file: ${{ inputs.tf-vars-file }}
          s3-bucket: ${{ vars.TF_STATE_BUCKET_NAME }}
          s3-region: ${{ vars.AWS_REGION }}
          ci-pipeline: ${{ inputs.ci-pipeline }}

  infra-cost:
    if: ${{ fromJSON(needs.execution-path.outputs.execution-path).IaC == true }}
    name: 💰 Infra Cost
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [terraform-plan]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-role-arn }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Infra Cost
        id: infra-cost
        uses: subhamay-bhattacharyya-gha/infracost-action@main
        with:
          terraform-dir: ${{ inputs.terraform-dir }} 
          ci-pipeline: ${{ inputs.ci-pipeline }}
          s3-bucket: ${{ vars.TF_STATE_BUCKET_NAME }}
          s3-region: ${{ vars.AWS_REGION }}
          infracost-api-key: ${{ secrets.infracost-api-key }}
          gist-id: ${{ secrets.infracost-gist-id }}
          environment: ${{ inputs.environment }}

  terraform-apply:
    if: ${{ fromJSON(needs.execution-path.outputs.execution-path).IaC == true }}
    name: 🚧 Terraform Apply
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [infra-cost]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-role-arn }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Apply
        uses: subhamay-bhattacharyya-gha/tf-apply-action@main
        id: apply
        with:
          terraform-dir: ${{ inputs.terraform-dir }}
          s3-bucket: ${{ vars.TF_STATE_BUCKET_NAME }}
          s3-region: ${{ vars.AWS_REGION }}
          ci-pipeline: ${{ inputs.ci-pipeline }}

  terraform-destroy:
    if: ${{ fromJSON(needs.execution-path.outputs.execution-path).IaC == true }}
    name: ✂️ Terraform Destroy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [terraform-apply]
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-role-arn }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Destroy
        uses: subhamay-bhattacharyya-gha/tf-destroy-action@main
        id: destroy
        with:
          terraform-dir: ${{ inputs.terraform-dir }}
          s3-bucket: ${{ vars.TF_STATE_BUCKET_NAME }}
          s3-region: ${{ vars.AWS_REGION }}
          ci-pipeline: ${{ inputs.ci-pipeline }}

  create-release:
    name: 🚀 Create Release
    runs-on: ubuntu-latest
    if: |
        (needs.build-lambda.result == 'success' ||
          needs.build-lambda-layer.result == 'success' ||
          needs.build-glue.result == 'success' ||
          needs.build-state-machine.result == 'success' ||
          needs.terraform-destroy.result == 'success')
    needs: 
    - build-lambda
    - build-lambda-layer
    - build-glue
    - build-state-machine
    - terraform-validate
    - terraform-lint
    - checkov-scan
    - infra-cost
    - terraform-plan
    - terraform-apply
    - terraform-destroy
    steps:
      - name: Create Release
        uses: subhamay-bhattacharyya-gha/create-release-action@feature/GHA-0002-initial-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}